### ISSUE TITLE
take offer

### ISSUE THREAD

**Issue by ronickg** [Chia-Mine/chia-agent#40]
Always getting this error when trying to use take_offer. All synced and wallet balance showing correctly. 
`{ error: 'clvm raise', success: false }`

Here's the code:
`async function snipeOffer(offer) {
  const agent = new RPCAgent({ service: "wallet" });
  const res = await take_offer(agent, { offer, fee: FEE });
  return res;
}
`

`snipeOffer(
  "offer1qqr83wcuu2rykcmqvpsxygqqemhmlaekcenaz02ma6hs5w600dhjlvfjn477nkwz369h88kll73h37fefnwk3qqnz8s0lle0vr8f925fp4gfm9su4vuj7kekfr9ul0xkf2x2ke2zfm65gaktd79hhq22xf8yl8y70a4sx4lerlzayrw94tfc880xkdhm88f87jszgat0nwtpufa5rrarsf0tuw60d7xme9red6nvtr86zlt7kk0crlkukwfue0ad4l7a0kvh4ae8gk0eaeu3hpwl0yz8t94mmu9wquwh9vgrjhu65q75kv385zhx7p35ugvxzvv8xndrwwj8xgay0unlwj8xgzxwj9qd9a5zlf25ds0maa08cu80xsnahf3mf8hthruufl5g7vyfzkmm480uvf9uml8lpd3rwfx6h5l0r7j2tt0pa2aw6jkkk4m6n96hv45hx35t52hun5dm0rmrc8aslf22ncqsjp7jhmj3htfekj7vaj4whr49faa6y5te07fd89aaqa396s4wfsnrw3ngvdsfvp6xvehcemxgqylusgzmau7re07y89kc8yvwe7ldm0qff47w92uk5kdjexap7ph7k8xfxr7p7fz7nlcr9yvj2fg9c4t047nedyju2f0egky7n2t68xvhnk06nyzkn306fxykn92f4xv5j924vmu6v7g9u4532ktf24rqt3vfq4vk2fwfdx5nj3293yucnz2xe9yjjeh9c5umnedxr9z4j339h8zkdp06ecvejwfen8zh5kg9a8lsl7yp3spa5s39qwq3an2curc0dnvw63279pdl4hz8df00fask8y92lj5p08lfrqvrg4lelh9fethll7dh9qf7fj3ejrmn2d93y5cjfvf0tv5270elu8cg5zpp75vvqnaty2g8azp5fxq0vqnpk409zut2w4vevsj9w9z4z6vzv9c4z3jp39m8jc2enxgc57t3weqer9j3v99yv4jk24z45c234eg4rxned65prjncw8syyx5u2ft6q55kjgym3te5qsapc5jjqv3hv0qeffckl2kf8a3447flk66jthppvamlw8yg7x62sh2etf4d56d07eh3s8wfdv0qvhtfljan2l7pr8tkmwl004pn4hjk0f29467slkdjylw8x27rla2j9l4sznu6lj7mfa7arg6ehmmv0n7dpk4t5l02ejhx66chf7crjmaawfu7df0tm4vg4l73m9zeghp782answ4mfrqrml68vutcnrf8ltxzusk2h636kh644e0u2gqa5fl8lsvf7d820u3dh6mys4lum37z32xcdmfn6af44qeptlan6alj6jwa09xrmmp47wgl3fek44rwangewv7fhxg7teu347tqzktzyun5zehhg9n09rxw9ld8wvmhysdyer46934dauxhlzl0dq6fghrcuh4ygh77jtua84fyyj95tyj6rcv5r9ypr5rhw8j6ccdtdwm2cqrxl69mwxhk97wkrd479legg5kp964d9wg049am79hwk2h4knng5l4kvuq32e7c0fmkm7h5mfnut8nar0tvs2wqetxqv482llls26a90w053wj7tmt8wtzhles89ynnavmlk360mtw9d89g2n8wchfhgh70lq3n9jskwxlan4p92layfueaj7em3nkeg5vn3mxmydtmtaj8ulraamej0vxtgq3kscq8qvdk7gqx9rq3qx3dsmjqzcphjjsy4y9ecsv00hl7lup0lgjyh0mk24c7n3txwdgd4a6l0dps0vgwrafsdh8wre3mm8wxwul9vpvh2c52de90xhx0kdz67wpnvt0q4n5ftfl7gc0mnxu45k6rxmyawuya9lnmc5tjcx3n3vfewjscl4zxcvts0wxj6exwm5t9ws507f434xk0kllsn527ymsufy4secl78ukxnauaaju70zccmw8wea465qvy0066ccq96qq4e398c4x9ts6"
).then((res) => console.log(res));`

**Comment by tojump** [comment]
Does it work if you try to call the RPC directly with the same arguments?

**Comment by ronickg** [comment]
Trying right now. Give me a sec

**Comment by ronickg** [comment]
Exception from 'wallet' {'error': 'clvm raise', 'success': False}:
Traceback (most recent call last):
  File "chia\cmds\cmds_util.py", line 100, in get_any_service_client
  File "chia\cmds\cmds_util.py", line 211, in execute_with_wallet
  File "chia\cmds\wallet_funcs.py", line 683, in take_offer
  File "chia\rpc\wallet_rpc_client.py", line 711, in take_offer
  File "chia\rpc\rpc_client.py", line 61, in fetch
ValueError: {'error': 'clvm raise', 'success': False}

**Comment by ronickg** [comment]
May be something buggy with my wallet. Ill try delete the db and sync up again.

**Comment by ronickg** [comment]
Issue was me trying to accept my own offer. Guess that doesn't work, good to know.
